### ISSUE TITLE
/usr/bin/optipng: no such file or directory

### ISSUE THREAD

**Issue by janpapenbrock** [buffcode/docker-optipng#2]
Hey, thanks for your efforts with this image.

Sadly, with the latest push to dockerhub it appears to have stopped working.

Steps to reproduce:
1. `docker pull buffcode/docker-optipng`
2. `docker run -v $PWD:/source buffcode/docker-optipng`

Result:
```container_linux.go:265: starting container process caused "exec: \"/usr/bin/optipng\": stat /usr/bin/optipng: no such file or directory"
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "exec: \"/usr/bin/optipng\": stat /usr/bin/optipng: no such file or directory".
ERRO[0000] error waiting for container: context canceled 
```

**Comment by janpapenbrock** [comment]
Apparently, during the build, the package is uninstalled again:

`Removing optipng (0.7.6-1) ...`

From build details https://hub.docker.com/r/buffcode/docker-optipng/builds/bapxghqzryzjeat6m55nzr3/

**Comment by buffcode** [comment]
Thanks for reporting!
I don't know why it suddenly broke, but this small commit fixes the problem.
